### ISSUE TITLE
USER STORY: Exploring Book Details

### ISSUE THREAD

**Issue by Camelia03** [Camelia03/portofolio-project-5#10]
As a **guest** or **registered user**, I can **view the details of a single book** so that **I can learn more about the book's summary, author, and user reviews but also a comments section**

## Acceptance Criteria:

- Users can click on a book to view its details.
- Book details include the title, author, description, and user reviews.
- Users can easily navigate back to the main book catalog.

## Tasks:

- [x]  Create a page for viewing individual book details.
- [x]  Design a user-friendly layout for book details.
- [x]  Implement a navigation system to return to the main book catalog.
