### ISSUE TITLE
USER STORY: Viewing All Books by a Specific Author

### ISSUE THREAD

**Issue by Camelia03** [Camelia03/portofolio-project-5#15]
As a **guest** or **registered user**, I can **see all books by a specific author** to **catch up on their latest publications or decide whether to follow them**.

## Acceptance Criteria:

- Readers can access an author's book catalog page.
- The page displays all books by the specific author.
- Readers can easily navigate back to the author's profile.

## Tasks:

- [x]  Create an author-specific book catalog page or section for displaying all books by the author.
- [x]  Implement the feature to list all books by the specific author.
- [x]  Add a link to return to the author's profile.
