### ISSUE TITLE
USER STORY: Editing Reader Profile

### ISSUE THREAD

**Issue by Camelia03** [Camelia03/portofolio-project-5#16]
As a **registered user**, I can **edit my profile, including changing my profile picture and bio** to **customize my reader profile**.

## Acceptance Criteria:

- Readers can access an edit profile page.
- Readers can modify their profile picture, bio, and other relevant information.
- Changes made to the profile are saved and reflected on the reader's profile.

## Tasks:

- [x]  Design and create an edit profile page for readers.
- [x]  Implement the ability to change the profile picture and bio.
- [x]  Ensure that changes are saved and reflected on the reader's profile.
