### ISSUE TITLE
USER STORY: Creating a New Account

### ISSUE THREAD

**Issue by Camelia03** [Camelia03/portofolio-project-5#3]
As a **guest** I can **create a new account** to **access all features for signed-up users**

## Acceptance criteria:
* As a user, I can create a new account to access all features reserved for registered users
* The sign-up page is functional, and users can access all features after signing up.

## Tasks:
- [x] Design and develop a sign-up page.
- [x] Implement user registration functionality.
- [x] Ensure all features for signed-up users are accessible upon registration.
